routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\RazorpayController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialLinkController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Front Routes
Route::get('/', [FrontController::class, 'index'])->name('front');
Route::get('/detail/{slug}', [FrontController::class, 'productDetail']);
Route::get('faq', [FrontController::class, 'faq'])->name('faq');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('shopping-cart', [FrontController::class, 'cart'])->name('cart');
Route::get('sign-in', [FrontController::class, 'signIn'])->name('sign-in');
Route::get('sign-up', [FrontController::class, 'signUp'])->name('sign-up');
Route::get('forgot-password', [FrontController::class, 'forgotPassword'])->name('forgot-password');
Route::get('reset-password', [FrontController::class, 'resetPassword'])->name('reset-password');

Auth::routes();

Route::get('/home', function () {
    return view('dashboard.dashboard.dashboard');
});

Route::resource('users', UserController::class);

Route::get('/coupons', function () {
    return view('dashboard.coupons.index');
});
Route::get('/create_coupon', function () {
    return view('dashboard.coupons.create');
});
Route::get('/test_index', function () {
    return view('dashboard.products.testing.indexed');
});
Route::get('/test_create', function () {
    return view('dashboard.products.testing.created');
});
Route::get('/test_show', function () {
    return view('dashboard.products.testing.showed');
});
Route::get('/test_update', function () {
    return view('dashboard.products.testing.edited');
});
Route::get('/orders', function () {
    return view('dashboard.orders.orders');
});
Route::get('/create_orders', function () {
    return view('dashboard.orders.create');
});
Route::get('/invoices', function () {
    return view('dashboard.invoices.index');
});

Route::get('/add_address', function () {
    return view('dashboard.settings.add_addresses');
});

Route::get('/add_languages', function () {
    return view('dashboard.settings.add_languages');
});
Route::get('/language-settings', function () {
    return view('dashboard.settings.language-settings.index');
});
Route::get('/smtp-settings', function () {
    return view('dashboard.settings.smtp-settings.create');
});
Route::get('/sms-settings', function () {
    return view('dashboard.settings.sms-settings.create');
});
Route::get('/addresses', function () {
    return view('dashboard.settings.addresses.index');
});
Route::get('/payments', function () {
    return view('dashboard.settings.payment-gateway-settings.create');
});
Route::get('settings', [SettingController::class, 'index'])->name('setting');
Route::resource('categories', CategoriesController::class);
Route::get('get-sub-categories/{categoryId}', [SubCategoryController::class, 'getSubcategories'])->name('get_sub_categories');
Route::resource('sub-categories', SubCategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('users', UserController::class);
Route::resource('general-settings', GeneralSettingController::class);
Route::resource('languages', LanguageSettingController::class);
Route::resource('social-links', SocialLinkController::class);
Route::resource('faqs', FaqController::class);
/* Payment Gateways */

// Stripe Payment
Route::get('/stripe-payment', [StripeController::class, 'handleGet']);
Route::post('/stripe-payment', [StripeController::class, 'handlePost'])->name('stripe.payment');

// Razorpay Payment
Route::get('razorpay-payment', [RazorpayController::class, 'index']);
Route::post('razorpay-payment', [RazorpayController::class, 'store'])->name('razorpay.payment.store');
Route::get('/index', [FrontController::class, 'index']);

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    use HasFactory;
    
 protected $fillable = [
    'title',
    'description',
    'status',
    'created_by',
    'updated_by',
     ];
}

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\Models\Faq;
use Illuminate\Http\Request;

class FaqController extends Controller
{

    public function index()
    {
        $faqs = Faq::get();
        return view('dashboard.settings.index', compact('faqs'));
    }

    public function create()
    {
        return view('dashboard.faqs.create');
    }

    public function store(Request $request)
    {
        $faqs = new Faq;
        $faqs->title = $request->title;
        $faqs->description = $request->description;
        $faqs->status = $request->status;
        $faqs->save();
        return redirect('/settings');
    }

    public function edit($id)
    {
        $faq = Faq::find($id);
        return view('dashboard.faqs.edit', compact('faq'));
    }

    public function update(Request $request,$id)
    {
        $faqs = Faq::find($id);
        $faqs->title = $request->title;
        $faqs->description = $request->description;
        $faqs->status = $request->status;
        $faqs->save();
        return redirect('/settings');
    }

    public function destroy($id)
    {
        Faq::find($id)->delete();
        return redirect('/settings');
    }
}

resources/views/dashboard/faqs/create.blade.php
@extends('layouts.base')

@section('title')

Create Faqs

@endsection
@section('content')
<body onload="createFaq()">

<script>
function createFaq(){
    $('#exampleModal').modal('show');
}
</script>
</body>

@endsection

resources/views/dashboard/faqs/edit.blade.php
@extends('layouts.base')

@section('title')

Update Faqs

@endsection
@section('content')
<body onload="editFaq()">
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Update FAQ</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="{{ route('faqs.update', $faqs->id) }}" method="post"  class="panel-body">
                @csrf
                @method('put')
                <strong>Update Faq Form</strong>
                <div class="wrapper wrapper-content animated fadeInRight">
                    <div class="row" style="margin-top: 2rem">
                        <div class="col-md-12">
                            <div class="form-group @error('title') has-error @enderror">
                                <label for="title" class="control-label"> Update Faq<span class="text-danger">*</span></label>
                                <input type="text" placeholder="Enter title here..." class="form-control" name="title" id="title" value="{{ $faqs->title }}">
                                @error('title')
                                    <span class="text-danger"> {{ $message }} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group @error('description') has-error @enderror">
                                <label for="description" class="control-label"> Description<span class="text-danger">*</span></label>
                                <input type="text" placeholder="Enter description here..." class="form-control" name="description" id="description" value="{{ $faqs->description }}">
                                @error('description')
                                    <span class="text-danger"> {{ $message }} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group @error('status') has-error @enderror">
                                <label for="status">Status <span class="text-danger">*</span></label>
                                <select class="form-control" name="status" id="status">
                                    <option>Select</option>
                                    <option value="active" {{ $faqs->status == 'active' ? 'selected' : '' }}>Active</option>
                                    <option value="inactive" {{ $faqs->status == 'inactive' ? 'selected' : '' }}>Inactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </form>

        </div>
        </div>
    </div>
</div>
<script>
function editFaq(){
    $('#exampleModal').modal('show');
}
</script>
</body>

@endsection