routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\RazorpayController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialLinkController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Front Routes
Route::get('/', [FrontController::class, 'index'])->name('front');
Route::get('/detail/{slug}', [FrontController::class, 'productDetail']);
Route::get('faq', [FrontController::class, 'faq'])->name('faq');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('shopping-cart', [FrontController::class, 'cart'])->name('cart');
Route::get('sign-in', [FrontController::class, 'signIn'])->name('sign-in');
Route::get('sign-up', [FrontController::class, 'signUp'])->name('sign-up');
Route::get('forgot-password', [FrontController::class, 'forgotPassword'])->name('forgot-password');
Route::get('reset-password', [FrontController::class, 'resetPassword'])->name('reset-password');

Auth::routes();

Route::get('/home', function () {
    return view('dashboard.dashboard.dashboard');
});

Route::resource('users', UserController::class);

Route::get('/coupons', function () {
    return view('dashboard.coupons.index');
});
Route::get('/create_coupon', function () {
    return view('dashboard.coupons.create');
});
Route::get('/test_index', function () {
    return view('dashboard.products.testing.indexed');
});
Route::get('/test_create', function () {
    return view('dashboard.products.testing.created');
});
Route::get('/test_show', function () {
    return view('dashboard.products.testing.showed');
});
Route::get('/test_update', function () {
    return view('dashboard.products.testing.edited');
});
Route::get('/orders', function () {
    return view('dashboard.orders.orders');
});
Route::get('/create_orders', function () {
    return view('dashboard.orders.create');
});
Route::get('/invoices', function () {
    return view('dashboard.invoices.index');
});

Route::get('/add_address', function () {
    return view('dashboard.settings.add_addresses');
});

Route::get('/add_languages', function () {
    return view('dashboard.settings.add_languages');
});
Route::get('/language-settings', function () {
    return view('dashboard.settings.language-settings.index');
});
Route::get('/smtp-settings', function () {
    return view('dashboard.settings.smtp-settings.create');
});
Route::get('/sms-settings', function () {
    return view('dashboard.settings.sms-settings.create');
});
Route::get('/addresses', function () {
    return view('dashboard.settings.addresses.index');
});
Route::get('/payments', function () {
    return view('dashboard.settings.payment-gateway-settings.create');
});
Route::get('settings', [SettingController::class, 'index'])->name('setting');
Route::resource('categories', CategoriesController::class);
Route::get('get-sub-categories/{categoryId}', [SubCategoryController::class, 'getSubcategories'])->name('get_sub_categories');
Route::resource('sub-categories', SubCategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('users', UserController::class);
Route::resource('general-settings', GeneralSettingController::class);
Route::resource('languages', LanguageSettingController::class);
Route::resource('social-links', SocialLinkController::class);
Route::resource('faqs', FaqController::class);
/* Payment Gateways */

// Stripe Payment
Route::get('/stripe-payment', [StripeController::class, 'handleGet']);
Route::post('/stripe-payment', [StripeController::class, 'handlePost'])->name('stripe.payment');

// Razorpay Payment
Route::get('razorpay-payment', [RazorpayController::class, 'index']);
Route::post('razorpay-payment', [RazorpayController::class, 'store'])->name('razorpay.payment.store');
Route::get('/index', [FrontController::class, 'index']);

app/Models/Product.php
<?php

namespace App\Models;

use App\Observers\ProductsObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected static function boot()
    {
        parent::boot();
        static::observe(ProductsObserver::class);
    }


    protected $fillable = [
        'name',
        'price',
        'descriptions',
        'photo',
        'quantity',
        'status',
        'created_by',
        'updated_by',
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Models\Categories;
use App\Models\Product;
use App\Models\SubCategory;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function index()
    {
        $products = Product::get();
        return view('dashboard.products.index', compact('products'));
    }

    public function create()
    {
        $categories = Categories::get();
        $subCategories = SubCategory::get();

        return view('dashboard.products.create', compact('categories', 'subCategories'));
    }

    // public function store(StoreProductRequest $request)
    public function store(Request $request)
    {
        $products = new Product;
        $products->category_id = $request->category_id;
        $products->sub_category_id = $request->sub_category_id;
        $products->name = $request->name;
        $products->price = $request->price;
        $products->quantity = $request->quantity;
        $products->description = $request->description;
        $products->status = $request->status;
        $products->save();

        return redirect('products')->with(['success' => 'Product added.']);
    }


    public function show($id)
    {
        $products = Product::find($id);
        $categories = Categories::get();
        $subCategories = SubCategory::get();
        return view('dashboard.products.show', compact('products', 'categories', 'subCategories'));
    }


    public function edit($id)
    {
        $products = Product::find($id);
        $categories = Categories::get();
        $subCategories = SubCategory::get();

        return view('dashboard.products.edit', compact('products', 'categories', 'subCategories'));
    }

    public function update(Request $request, $id)
    {
        $products = Product::find($id);
        $products->name = $request->name;
        $products->price = $request->price;
        $products->quantity = $request->quantity;
        $products->description = $request->description;
        $products->status = $request->status;
        $products->save();

        return redirect('/products')->with(['success' => 'User has been updated.']);
    }

    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect('/products')->with(['success' => 'User has been deleted.']);
    }
}

resources/views/dashboard/products/create.blade.php
@extends('layouts.base')

@section('title')
    Add Product
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
        integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{{ asset('asset/css/plugins/summernote/summernote.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/summernote/summernote-bs3.css') }}" rel="stylesheet">

    <link href="{{ asset('asset/css/plugins/dropzone/basic.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/dropzone/dropzone.css') }}" rel="stylesheet">
@endsection
@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Add Products</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{{ route('products.index') }}">Manage Product</a>
                </li>

                <li>
                    <a href="{{ route('products.index') }}">Products</a>
                </li>
                <li class="active">
                    <strong>Add Product</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
            <a href="{{ route('products.index') }}" class="btn btn-warning mt-3" id="save-data">
                <span class="fa fa-arrow-left"></span>
                Back
            </a>
            <button class="btn btn-primary mt-3" id="save-data"> <span class="fa fa-save"></span> Save</button>
        </div>

    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Product Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group @error('category_id') has-error @enderror">
                                        <label for="category_id">Category <span class="text-danger">*</span></label>
                                        <select class="form-control" name="category_id" id="category_id">
                                            <option>Select</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="category_id">Sub-Category </label>
                                        <select class="form-control" name="sub_category_id" id="sub_category_id">
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('product_name') has-error @enderror">
                                        <label for="product_name">Product Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter product_name" class="form-control" name="name"
                                            id="product_name" value="{{ old('product_name') }}">
                                        @error('product_name')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('price') has-error @enderror">
                                        <label for="price">Price <span class="text-danger">*</span></label>
                                        <input type="price" class="form-control" placeholder="Enter price" name="price"
                                            id="price" value="{{ old('price') }}">
                                        @error('price')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('quantity') has-error @enderror">
                                        <label for="quantity">Quantity <span class="text-danger">*</span></label>
                                        <input type="number" class="form-control" placeholder="Enter quantity"
                                            name="quantity" id="quantity" value="{{ old('quantity') }}">
                                        @error('quantity')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('description') has-error @enderror">
                                        <label for="description">Description <span class="text-danger">*</span></label>
                                        {{-- <input type="text" class="form-control" placeholder="Enter desription" --}}
                                            {{-- name="description" id="description" value="{{ old('description') }}"> --}}

                                        <textarea class="form-control summernote" name="description" id="description">
                                        </textarea>

                                        @error('description')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option>Select</option>
                                            <option value="active">active</option>
                                            <option value="inactive">inactive</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
        </div>
    </div>

@endsection
@section('script')

    <script src="{{ asset('asset/js/jquery-2.1.1.js') }}"></script>
    <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- ck editor -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
        integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- SUMMERNOTE -->
    <script src="{{ asset('asset/js/plugins/summernote/summernote.min.js') }}"></script>

    <!-- DROPZONE -->
    <script src="{{ asset('asset/js/plugins/dropzone/dropzone.js') }}"></script>

    <script>
        $('.dropify').dropify();


        $(document).ready(function() {
            Dropzone.options.myAwesomeDropzone = {
                autoProcessQueue: false,
                uploadMultiple: true,
                parallelUploads: 100,
                maxFiles: 100,

                // Dropzone settings
                init: function() {
                    var myDropzone = this;

                    this.element
                        .querySelector("button[type=submit]")
                        .addEventListener("click", function(e) {
                            e.preventDefault();
                            e.stopPropagation();
                            myDropzone.processQueue();
                        });
                    this.on("sendingmultiple", function() {});
                    this.on("successmultiple", function(files, response) {});
                    this.on("errormultiple", function(files, response) {});
                },
            };
        });



        $('.summernote').summernote();

        var edit = function() {
            $('.click2edit').summernote({
                focus: true
            });
        };
        var save = function() {
            var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
            $('.click2edit').destroy();
        };

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        });

        $(document).on('change', '#category_id', function() {

            var categoryId = $(this).val();

            let url = "{{ route('get_sub_categories', ':id') }}";
            url = url.replace(':id', categoryId);

            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    $('#sub_category_id').html(response);
                }
            });

        });

    </script>

@endsection

resources/views/dashboard/products/edit.blade.php
@extends('layouts.base')

@section('title')
    Edit Products
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
        integrity="sha512-EZSUkJWTjzDlspOoPSpUFR0o0Xy7jdzW//6qhUkoZ9c4StFkVsp9fbbd0O06p9ELS3H486m4wmrCELjza4JEog=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{{ asset('asset/css/plugins/summernote/summernote.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/summernote/summernote-bs3.css') }}" rel="stylesheet">

    <link href="{{ asset('asset/css/plugins/dropzone/basic.css') }}" rel="stylesheet">
    <link href="{{ asset('asset/css/plugins/dropzone/dropzone.css') }}" rel="stylesheet">
@endsection
@section('breadcrum')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2> Products </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{{ route('products.index') }}">Manage Product</a>
                </li>
                <li>
                    <a href="{{ route('products.index') }}">Products</a>
                </li>

                <li class="active">
                    <strong>Edit Products</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-3">
            <a href="{{ route('products.index') }}" class="btn btn-warning mt-3" id="save-data">
                <span class="fa fa-arrow-left"></span>
                Back
            </a>
             <button class="btn btn-primary mt-3" id="save-data">
                    <span class="fa fa-save"></span> Edit & Save </button>
        </div>

    </div>
@endsection

@section('content')
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <form action="{{ route('products.update',$products->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Product Details</h3>
                        </div>
                        <div class="ibox-content">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group @error('category_id') has-error @enderror">
                                        <label for="category_id">Category <span class="text-danger">*</span></label>
                                        <select class="form-control" name="category_id" id="category_id">
                                            <option>Select</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}"@if($category->id == $products->id) selected @endif  >{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="category_id">Sub-Category </label>
                                        <select class="form-control" name="sub_category_id" id="sub_category_id" >
                                            @foreach ($subCategories as $subCategory)
                                                <option value="{{ $subCategory->id }}"@if($subCategory->id == $products->id) selected @endif  >{{ $subCategory->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="col-md-12">
                                    <div class="form-group @error('product_name') has-error @enderror">
                                        <label for="product_name">Product Name <span class="text-danger">*</span></label>
                                        <input type="text" placeholder="Enter product_name" class="form-control" name="name"
                                            id="product_name" value="{{ $products->name }}">
                                        @error('product_name')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('price') has-error @enderror">
                                        <label for="price">Price <span class="text-danger">*</span></label>
                                        <input type="price" class="form-control" placeholder="Enter price" name="price"
                                            id="price" value="{{ $products->price }}">
                                        @error('price')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('quantity') has-error @enderror">
                                        <label for="quantity">Quantity <span class="text-danger">*</span></label>
                                        <input type="quantity" class="form-control" placeholder="Enter quantity"
                                            name="quantity" id="quantity" value="{{ $products->quantity }}">
                                        @error('quantity')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group @error('description') has-error @enderror">
                                        <label for="description">Description <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" placeholder="Enter desription"
                                            name="description" id="description" value="{{ $products->description }}">
                                        @error('description')
                                            <span class="text-danger"> {{ $message }} </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group @error('status') has-error @enderror">
                                        <label for="status">Status <span class="text-danger">*</span></label>
                                        <select class="form-control" name="status" id="state">
                                            <option>Select</option>
                                            <option value="active"
                                                {{ $products->status == 'active' ? 'selected' : '' }}>active</option>
                                            <option value="inactive"
                                                {{ $products->status == 'inactive' ? 'selected' : '' }}>inactive
                                            </option>
                                        </select>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

            </form>


        </div>
    </div>

@endsection

@section('script')
    <script src="{{ asset('asset/js/jquery-2.1.1.js') }}"></script>
    <script src="{{ asset('asset/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/metisMenu/jquery.metisMenu.js') }}"></script>
    <script src="{{ asset('asset/js/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- ck editor -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
        integrity="sha512-8QFTrG0oeOiyWo/VM9Y8kgxdlCryqhIxVeRpWSezdRRAvarxVtwLnGroJgnVW9/XBRduxO/z1GblzPrMQoeuew=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- SUMMERNOTE -->
    <script src="{{ asset('asset/js/plugins/summernote/summernote.min.js') }}"></script>

    <!-- DROPZONE -->
    <script src="{{ asset('asset/js/plugins/dropzone/dropzone.js') }}"></script>
    <script>
        $('.dropify').dropify();


        $(document).ready(function() {
            Dropzone.options.myAwesomeDropzone = {
                autoProcessQueue: false,
                uploadMultiple: true,
                parallelUploads: 100,
                maxFiles: 100,

                // Dropzone settings
                init: function() {
                    var myDropzone = this;

                    this.element
                        .querySelector("button[type=submit]")
                        .addEventListener("click", function(e) {
                            e.preventDefault();
                            e.stopPropagation();
                            myDropzone.processQueue();
                        });
                    this.on("sendingmultiple", function() {});
                    this.on("successmultiple", function(files, response) {});
                    this.on("errormultiple", function(files, response) {});
                },
            };
        });




        $('.summernote').summernote();

        var edit = function() {
            $('.click2edit').summernote({
                focus: true
            });
        };
        var save = function() {
            var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
            $('.click2edit').destroy();
        };

        $(document).on('click', '#save-data', function() {
            $('form').submit();
        })

        $(document).on('change', '#category_id', function() {
            var categoryId = $(this).val();
            let url = "{{ route('get_sub_categories', ':id') }}";
            url = url.replace(':id', categoryId);

            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    $('#sub_category_id').html(response);
                }
            });

         });

    </script>

@endsection