routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\GeneralSettingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\LanguageSettingController;
use App\Http\Controllers\StripeController;
use App\Http\Controllers\RazorpayController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SocialLinkController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Front Routes
Route::get('/', [FrontController::class, 'index'])->name('front');
Route::get('/detail/{slug}', [FrontController::class, 'productDetail']);
Route::get('faq', [FrontController::class, 'faq'])->name('faq');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('shopping-cart', [FrontController::class, 'cart'])->name('cart');
Route::get('sign-in', [FrontController::class, 'signIn'])->name('sign-in');
Route::get('sign-up', [FrontController::class, 'signUp'])->name('sign-up');
Route::get('forgot-password', [FrontController::class, 'forgotPassword'])->name('forgot-password');
Route::get('reset-password', [FrontController::class, 'resetPassword'])->name('reset-password');

Auth::routes();

Route::get('/home', function () {
    return view('dashboard.dashboard.dashboard');
});

Route::resource('users', UserController::class);

Route::get('/coupons', function () {
    return view('dashboard.coupons.index');
});
Route::get('/create_coupon', function () {
    return view('dashboard.coupons.create');
});
Route::get('/test_index', function () {
    return view('dashboard.products.testing.indexed');
});
Route::get('/test_create', function () {
    return view('dashboard.products.testing.created');
});
Route::get('/test_show', function () {
    return view('dashboard.products.testing.showed');
});
Route::get('/test_update', function () {
    return view('dashboard.products.testing.edited');
});
Route::get('/orders', function () {
    return view('dashboard.orders.orders');
});
Route::get('/create_orders', function () {
    return view('dashboard.orders.create');
});
Route::get('/invoices', function () {
    return view('dashboard.invoices.index');
});

Route::get('/add_address', function () {
    return view('dashboard.settings.add_addresses');
});

Route::get('/add_languages', function () {
    return view('dashboard.settings.add_languages');
});
Route::get('/language-settings', function () {
    return view('dashboard.settings.language-settings.index');
});
Route::get('/smtp-settings', function () {
    return view('dashboard.settings.smtp-settings.create');
});
Route::get('/sms-settings', function () {
    return view('dashboard.settings.sms-settings.create');
});
Route::get('/addresses', function () {
    return view('dashboard.settings.addresses.index');
});
Route::get('/payments', function () {
    return view('dashboard.settings.payment-gateway-settings.create');
});
Route::get('settings', [SettingController::class, 'index'])->name('setting');
Route::resource('categories', CategoriesController::class);
Route::get('get-sub-categories/{categoryId}', [SubCategoryController::class, 'getSubcategories'])->name('get_sub_categories');
Route::resource('sub-categories', SubCategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('users', UserController::class);
Route::resource('general-settings', GeneralSettingController::class);
Route::resource('languages', LanguageSettingController::class);
Route::resource('social-links', SocialLinkController::class);
Route::resource('faqs', FaqController::class);
/* Payment Gateways */

// Stripe Payment
Route::get('/stripe-payment', [StripeController::class, 'handleGet']);
Route::post('/stripe-payment', [StripeController::class, 'handlePost'])->name('stripe.payment');

// Razorpay Payment
Route::get('razorpay-payment', [RazorpayController::class, 'index']);
Route::post('razorpay-payment', [RazorpayController::class, 'store'])->name('razorpay.payment.store');
Route::get('/index', [FrontController::class, 'index']);

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    {{-- Bootstrap --}}
    <link href="{{ asset('asset/css/bootstrap.min.css') }}" rel="stylesheet">


    {{-- Font Awesome --}}
    <link href="{{ asset('asset/font-awesome/css/font-awesome.css') }}" rel="stylesheet">

    {{-- Animate Css --}}
    <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">

    @yield('css')
</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                                <img alt="image" class="img-circle"
                                    src="{{ asset('asset/img/profile_small.jpg') }}" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear"> <span class="block m-t-xs"> <strong
                                            class="font-bold">Admin</strong>
                                    </span> <span class="text-muted text-xs block">Manager<b class="caret"></b></span>
                                </span> </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="#">Profile</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li class="active">
                        <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
                    </li>
                    <li>
                        <a href="{{ route('users.index') }}"><i class="fa fa-users"></i> <span
                                class="nav-label">Users</span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Manage
                                Products</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="{{ route('categories.index') }}">Category</a></li>
                            <li><a href="{{ route('sub-categories.index') }}">Sub Category</a></li>
                            <li><a href="{{ route('products.index') }}">Products</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="/coupons"><i class="fa fa-money"></i> <span class="nav-label">Coupons</span>
                        </a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Manage
                                Orders</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="/orders">Orders</a></li>
                            <li><a href="/invoices">Invoices</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-pie-chart"></i> <span class="nav-label">Reports</span></a>
                    </li>
                    <li>
                        <a href="{{ route('setting') }}"><i class="fa fa-gears"></i> <span class="nav-label">Settings</span></a>                    </li>
                </ul>

            </div>
        </nav>
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i
                                class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control"
                                    name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Welcome Admin</span>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i> <span class="label label-warning">0</span>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i> <span class="label label-primary">0</span>
                            </a>
                        </li>
                        <li>
                            <a href="login.html">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            @yield('breadcrum')
            @yield('content')
            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Copyright</strong> Example Company &copy; 2014-2015
                </div>
            </div>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{{ asset('js/dashboard.js') }}"></script>

    <script>
        $(document).ready(function() {


            const modal = '#modal';
            const modal_heading = '#modelHeading';

            $('.users-table').DataTable();

            toastr.options = {
                "closeButton": true,
                "debug": true,
                "progressBar": true,
                "preventDuplicates": false,
                "positionClass": "toast-top-right",
                "onclick": null,
                "showDuration": "400",
                "hideDuration": "1000",
                "timeOut": "7000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
        });
    </script>

    @yield('script')
</body>

</html>